package presentation;

import dao.*;
import factory.*;
import transferObject.*;
import java.util.*;
import javax.swing.text.*;  // pour DateFormatter
import java.text.*;         // pour DateFormat
import javax.swing.*;

public class JDSeanceUpdate extends javax.swing.JDialog {
    
    /** Creates new form JDApparInsert */
    public JDSeanceUpdate(java.awt.Frame parent, String titre, Seance s) {
        super(parent, titre, true);
        initComponents();
        fillComponents(s);
        getRootPane().setDefaultButton(jButtonOK);
        setLocation(parent.getX()+parent.getWidth()/3, parent.getY()+parent.getHeight()/3);
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboFilm = new javax.swing.JComboBox();
        jComboJour = new javax.swing.JComboBox();
        jComboHeure = new javax.swing.JComboBox();
        jComboSalle = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonAnnul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Jour");

        jLabel3.setText("Heure");

        jLabel4.setText("Salle");

        jLabel1.setText("Film");

        jLabel5.setText("id");

        jTextId.setEditable(false);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel4)
                    .add(jLabel3)
                    .add(jLabel5))
                .add(28, 28, 28)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jComboFilm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jComboJour, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jComboHeure, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jComboSalle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jTextId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jComboFilm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jComboJour, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jComboHeure, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jComboSalle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(83, 83, 83))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonOK);

        jButtonAnnul.setText("Annuler");
        jButtonAnnul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAnnul);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnnulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonAnnulActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
// TODO add your handling code here:
        Seance s =new Seance();
        s.setId(Integer.parseInt(jTextId.getText()));
        s.setFilm((Film)jComboFilm.getSelectedItem());
        s.setJour((Jour)jComboJour.getSelectedItem());
        s.setHeure((Heure)jComboHeure.getSelectedItem());
        s.setSalle((Salle)jComboSalle.getSelectedItem());
        boolean ok = daoSea.updateSeance(s);
        if (!ok)
            JOptionPane.showMessageDialog(null,"Modification impossible !","Avertissement",JOptionPane.ERROR_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed
    
    private void fillComponents(Seance s)
    {
        ArrayList <Jour> j = daoJour.selectJours();
        for (int i=0;i<j.size();i++){
            jComboJour.addItem(j.get(i));
        }
        ArrayList <Heure> h = daoHeure.selectHeures();
        for (int i=0;i<h.size();i++){
            jComboHeure.addItem(h.get(i));
        }
        ArrayList <Salle> salle = daoSalle.selectSalles();
        for (int i=0;i<salle.size();i++){
            jComboSalle.addItem(salle.get(i));
        }
        ArrayList <Film> f = daoFilm.selectFilms();
        for (int i=0;i<f.size();i++){
            jComboFilm.addItem(f.get(i));
        }
        int k=s.getId();
        jTextId.setText(String.valueOf(k));
        jComboJour.setSelectedIndex(s.getJour().getIdJour()-1);
        jComboHeure.setSelectedIndex(s.getHeure().getIdHeure()-1);
        jComboSalle.setSelectedIndex(s.getSalle().getIdSalle()-1);
        jComboFilm.setSelectedItem(s.getFilm());
        
        
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnul;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboFilm;
    private javax.swing.JComboBox jComboHeure;
    private javax.swing.JComboBox jComboJour;
    private javax.swing.JComboBox jComboSalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextId;
    // End of variables declaration//GEN-END:variables
    private DAOSeance daoSea = Factory.getDAOSeance();
    private DAOJour daoJour= Factory.getDAOJour();
    private DAOHeure daoHeure = Factory.getDAOHeure();
    private DAOSalle daoSalle = Factory.getDAOSalle();
    private DAOFilm daoFilm = Factory.getDAOFilm();

}
