package presentation;

import dao.*;
import factory.*;
import transferObject.*;
import model.*;
import javax.swing.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class JIFJour extends javax.swing.JInternalFrame {
    
    /** Creates new form FenetreJours */
    public JIFJour() {
        //((BasicInternalFrameUI) getUI()).setNorthPane(null);
        initComponents();
        System.out.println(myModel.getElementAt(0));
        refreshModel(); // nécessaire?
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListJour = new javax.swing.JList();

        setBorder(null);
        setTitle("Catégories");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setVisible(true);

        jLabel1.setText("Catégories :");

        jListJour.setModel(myModel);
        jListJour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListJourMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListJour);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListJourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListJourMouseClicked
        /*if (evt.getClickCount() == 2)
        {
            Jour objJour;
            
            String nouvJour = JOptionPane.showInputDialog(this,"Entrez le nouveau nom de catégorie",(String)jListJour.getSelectedValue());
            if (nouvJour != null)
            {
                nouvJour = nouvJour.substring(0, 1).toUpperCase() + nouvJour.substring(1);//1ère lettre en majuscule
                objJour = myModel.getMyList(jListJour.getSelectedIndex());
                objJour.setDenomJour(nouvJour);
                boolean ok = daoJour.updateJour(objJour);
                if (!ok)
                    JOptionPane.showMessageDialog(this,"Modification impossible !","Avertissement",JOptionPane.ERROR_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(this,"Opération annulée !","Avertissement",JOptionPane.ERROR_MESSAGE);
            // après : rafraîchir la liste
            refreshModel();
        }*/
    }//GEN-LAST:event_jListJourMouseClicked
    
       
    private void refreshModel()
    {
        myModel.setMyList(daoJour.selectJours());
        
        // pas de fire car il est compris dans setMyList
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListJour;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private DAOJour daoJour = Factory.getDAOJour();
    private ListModelJour myModel = new ListModelJour(daoJour.selectJours());
}
